// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cochlear_sense.proto

package com.cochlear.ai;

public final class CochlearSense {
  private CochlearSense() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface inputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cochlear.ai.input)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string subtask = 2;</code>
     */
    String getSubtask();
    /**
     * <code>string subtask = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubtaskBytes();

    /**
     * <code>string apikey = 3;</code>
     */
    String getApikey();
    /**
     * <code>string apikey = 3;</code>
     */
    com.google.protobuf.ByteString
        getApikeyBytes();

    /**
     * <code>string format = 4;</code>
     */
    String getFormat();
    /**
     * <code>string format = 4;</code>
     */
    com.google.protobuf.ByteString
        getFormatBytes();

    /**
     * <code>string dtype = 5;</code>
     */
    String getDtype();
    /**
     * <code>string dtype = 5;</code>
     */
    com.google.protobuf.ByteString
        getDtypeBytes();

    /**
     * <code>int32 sr = 6;</code>
     */
    int getSr();
  }
  /**
   * Protobuf type {@code cochlear.ai.input}
   */
  public  static final class input extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cochlear.ai.input)
      inputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use input.newBuilder() to construct.
    private input(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private input() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      subtask_ = "";
      apikey_ = "";
      format_ = "";
      dtype_ = "";
      sr_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private input(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              data_ = input.readBytes();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              subtask_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              apikey_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              format_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              dtype_ = s;
              break;
            }
            case 48: {

              sr_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CochlearSense.internal_static_cochlear_ai_input_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CochlearSense.internal_static_cochlear_ai_input_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              input.class, Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int SUBTASK_FIELD_NUMBER = 2;
    private volatile Object subtask_;
    /**
     * <code>string subtask = 2;</code>
     */
    public String getSubtask() {
      Object ref = subtask_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subtask_ = s;
        return s;
      }
    }
    /**
     * <code>string subtask = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubtaskBytes() {
      Object ref = subtask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subtask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APIKEY_FIELD_NUMBER = 3;
    private volatile Object apikey_;
    /**
     * <code>string apikey = 3;</code>
     */
    public String getApikey() {
      Object ref = apikey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        apikey_ = s;
        return s;
      }
    }
    /**
     * <code>string apikey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getApikeyBytes() {
      Object ref = apikey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        apikey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FORMAT_FIELD_NUMBER = 4;
    private volatile Object format_;
    /**
     * <code>string format = 4;</code>
     */
    public String getFormat() {
      Object ref = format_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        format_ = s;
        return s;
      }
    }
    /**
     * <code>string format = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFormatBytes() {
      Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DTYPE_FIELD_NUMBER = 5;
    private volatile Object dtype_;
    /**
     * <code>string dtype = 5;</code>
     */
    public String getDtype() {
      Object ref = dtype_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dtype_ = s;
        return s;
      }
    }
    /**
     * <code>string dtype = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDtypeBytes() {
      Object ref = dtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SR_FIELD_NUMBER = 6;
    private int sr_;
    /**
     * <code>int32 sr = 6;</code>
     */
    public int getSr() {
      return sr_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (!getSubtaskBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subtask_);
      }
      if (!getApikeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, apikey_);
      }
      if (!getFormatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, format_);
      }
      if (!getDtypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dtype_);
      }
      if (sr_ != 0) {
        output.writeInt32(6, sr_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (!getSubtaskBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subtask_);
      }
      if (!getApikeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, apikey_);
      }
      if (!getFormatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, format_);
      }
      if (!getDtypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dtype_);
      }
      if (sr_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, sr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof input)) {
        return super.equals(obj);
      }
      input other = (input) obj;

      boolean result = true;
      result = result && getData()
          .equals(other.getData());
      result = result && getSubtask()
          .equals(other.getSubtask());
      result = result && getApikey()
          .equals(other.getApikey());
      result = result && getFormat()
          .equals(other.getFormat());
      result = result && getDtype()
          .equals(other.getDtype());
      result = result && (getSr()
          == other.getSr());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + SUBTASK_FIELD_NUMBER;
      hash = (53 * hash) + getSubtask().hashCode();
      hash = (37 * hash) + APIKEY_FIELD_NUMBER;
      hash = (53 * hash) + getApikey().hashCode();
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormat().hashCode();
      hash = (37 * hash) + DTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDtype().hashCode();
      hash = (37 * hash) + SR_FIELD_NUMBER;
      hash = (53 * hash) + getSr();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static input parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static input parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static input parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static input parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static input parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static input parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static input parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static input parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static input parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static input parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static input parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static input parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(input prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cochlear.ai.input}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cochlear.ai.input)
        inputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CochlearSense.internal_static_cochlear_ai_input_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CochlearSense.internal_static_cochlear_ai_input_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                input.class, Builder.class);
      }

      // Construct using com.cochlear.ai.CochlearSense.input.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        subtask_ = "";

        apikey_ = "";

        format_ = "";

        dtype_ = "";

        sr_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CochlearSense.internal_static_cochlear_ai_input_descriptor;
      }

      public input getDefaultInstanceForType() {
        return input.getDefaultInstance();
      }

      public input build() {
        input result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public input buildPartial() {
        input result = new input(this);
        result.data_ = data_;
        result.subtask_ = subtask_;
        result.apikey_ = apikey_;
        result.format_ = format_;
        result.dtype_ = dtype_;
        result.sr_ = sr_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof input) {
          return mergeFrom((input)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(input other) {
        if (other == input.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getSubtask().isEmpty()) {
          subtask_ = other.subtask_;
          onChanged();
        }
        if (!other.getApikey().isEmpty()) {
          apikey_ = other.apikey_;
          onChanged();
        }
        if (!other.getFormat().isEmpty()) {
          format_ = other.format_;
          onChanged();
        }
        if (!other.getDtype().isEmpty()) {
          dtype_ = other.dtype_;
          onChanged();
        }
        if (other.getSr() != 0) {
          setSr(other.getSr());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CochlearSense.input parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CochlearSense.input) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private Object subtask_ = "";
      /**
       * <code>string subtask = 2;</code>
       */
      public String getSubtask() {
        Object ref = subtask_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subtask_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string subtask = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubtaskBytes() {
        Object ref = subtask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subtask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subtask = 2;</code>
       */
      public Builder setSubtask(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subtask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subtask = 2;</code>
       */
      public Builder clearSubtask() {
        
        subtask_ = getDefaultInstance().getSubtask();
        onChanged();
        return this;
      }
      /**
       * <code>string subtask = 2;</code>
       */
      public Builder setSubtaskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subtask_ = value;
        onChanged();
        return this;
      }

      private Object apikey_ = "";
      /**
       * <code>string apikey = 3;</code>
       */
      public String getApikey() {
        Object ref = apikey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          apikey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string apikey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getApikeyBytes() {
        Object ref = apikey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          apikey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string apikey = 3;</code>
       */
      public Builder setApikey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apikey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string apikey = 3;</code>
       */
      public Builder clearApikey() {
        
        apikey_ = getDefaultInstance().getApikey();
        onChanged();
        return this;
      }
      /**
       * <code>string apikey = 3;</code>
       */
      public Builder setApikeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apikey_ = value;
        onChanged();
        return this;
      }

      private Object format_ = "";
      /**
       * <code>string format = 4;</code>
       */
      public String getFormat() {
        Object ref = format_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string format = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFormatBytes() {
        Object ref = format_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          format_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string format = 4;</code>
       */
      public Builder setFormat(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        format_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string format = 4;</code>
       */
      public Builder clearFormat() {
        
        format_ = getDefaultInstance().getFormat();
        onChanged();
        return this;
      }
      /**
       * <code>string format = 4;</code>
       */
      public Builder setFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        format_ = value;
        onChanged();
        return this;
      }

      private Object dtype_ = "";
      /**
       * <code>string dtype = 5;</code>
       */
      public String getDtype() {
        Object ref = dtype_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dtype_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string dtype = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDtypeBytes() {
        Object ref = dtype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dtype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dtype = 5;</code>
       */
      public Builder setDtype(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dtype = 5;</code>
       */
      public Builder clearDtype() {
        
        dtype_ = getDefaultInstance().getDtype();
        onChanged();
        return this;
      }
      /**
       * <code>string dtype = 5;</code>
       */
      public Builder setDtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dtype_ = value;
        onChanged();
        return this;
      }

      private int sr_ ;
      /**
       * <code>int32 sr = 6;</code>
       */
      public int getSr() {
        return sr_;
      }
      /**
       * <code>int32 sr = 6;</code>
       */
      public Builder setSr(int value) {
        
        sr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sr = 6;</code>
       */
      public Builder clearSr() {
        
        sr_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cochlear.ai.input)
    }

    // @@protoc_insertion_point(class_scope:cochlear.ai.input)
    private static final input DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new input();
    }

    public static input getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<input>
        PARSER = new com.google.protobuf.AbstractParser<input>() {
      public input parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new input(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<input> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<input> getParserForType() {
      return PARSER;
    }

    public input getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface outputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cochlear.ai.output)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pred = 7;</code>
     */
    String getPred();
    /**
     * <code>string pred = 7;</code>
     */
    com.google.protobuf.ByteString
        getPredBytes();
  }
  /**
   * Protobuf type {@code cochlear.ai.output}
   */
  public  static final class output extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cochlear.ai.output)
      outputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use output.newBuilder() to construct.
    private output(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private output() {
      pred_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private output(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              pred_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CochlearSense.internal_static_cochlear_ai_output_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CochlearSense.internal_static_cochlear_ai_output_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              output.class, Builder.class);
    }

    public static final int PRED_FIELD_NUMBER = 7;
    private volatile Object pred_;
    /**
     * <code>string pred = 7;</code>
     */
    public String getPred() {
      Object ref = pred_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pred_ = s;
        return s;
      }
    }
    /**
     * <code>string pred = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPredBytes() {
      Object ref = pred_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pred_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPredBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pred_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPredBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pred_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof output)) {
        return super.equals(obj);
      }
      output other = (output) obj;

      boolean result = true;
      result = result && getPred()
          .equals(other.getPred());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRED_FIELD_NUMBER;
      hash = (53 * hash) + getPred().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static output parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static output parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static output parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static output parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static output parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static output parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static output parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static output parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static output parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static output parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static output parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static output parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(output prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cochlear.ai.output}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cochlear.ai.output)
        outputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CochlearSense.internal_static_cochlear_ai_output_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CochlearSense.internal_static_cochlear_ai_output_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                output.class, Builder.class);
      }

      // Construct using com.cochlear.ai.CochlearSense.output.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pred_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CochlearSense.internal_static_cochlear_ai_output_descriptor;
      }

      public output getDefaultInstanceForType() {
        return output.getDefaultInstance();
      }

      public output build() {
        output result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public output buildPartial() {
        output result = new output(this);
        result.pred_ = pred_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof output) {
          return mergeFrom((output)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(output other) {
        if (other == output.getDefaultInstance()) return this;
        if (!other.getPred().isEmpty()) {
          pred_ = other.pred_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        output parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (output) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object pred_ = "";
      /**
       * <code>string pred = 7;</code>
       */
      public String getPred() {
        Object ref = pred_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pred_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pred = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPredBytes() {
        Object ref = pred_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pred_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pred = 7;</code>
       */
      public Builder setPred(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pred_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pred = 7;</code>
       */
      public Builder clearPred() {
        
        pred_ = getDefaultInstance().getPred();
        onChanged();
        return this;
      }
      /**
       * <code>string pred = 7;</code>
       */
      public Builder setPredBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pred_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cochlear.ai.output)
    }

    // @@protoc_insertion_point(class_scope:cochlear.ai.output)
    private static final output DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new output();
    }

    public static output getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<output>
        PARSER = new com.google.protobuf.AbstractParser<output>() {
      public output parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new output(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<output> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<output> getParserForType() {
      return PARSER;
    }

    public output getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cochlear_ai_input_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cochlear_ai_input_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cochlear_ai_output_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cochlear_ai_output_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024cochlear_sense.proto\022\013cochlear.ai\"a\n\005i" +
      "nput\022\014\n\004data\030\001 \001(\014\022\017\n\007subtask\030\002 \001(\t\022\016\n\006a" +
      "pikey\030\003 \001(\t\022\016\n\006format\030\004 \001(\t\022\r\n\005dtype\030\005 \001" +
      "(\t\022\n\n\002sr\030\006 \001(\005\"\026\n\006output\022\014\n\004pred\030\007 \001(\t2\212" +
      "\007\n\016cochlear_sense\0224\n\005event\022\022.cochlear.ai" +
      ".input\032\023.cochlear.ai.output\"\000(\001\0229\n\nage_g" +
      "ender\022\022.cochlear.ai.input\032\023.cochlear.ai." +
      "output\"\000(\001\0228\n\tmusic_key\022\022.cochlear.ai.in" +
      "put\032\023.cochlear.ai.output\"\000(\001\022:\n\013music_te" +
      "mpo\022\022.cochlear.ai.input\032\023.cochlear.ai.ou" +
      "tput\"\000(\001\022:\n\013music_genre\022\022.cochlear.ai.in" +
      "put\032\023.cochlear.ai.output\"\000(\001\0229\n\nmusic_mo" +
      "od\022\022.cochlear.ai.input\032\023.cochlear.ai.out" +
      "put\"\000(\001\022=\n\016music_detector\022\022.cochlear.ai." +
      "input\032\023.cochlear.ai.output\"\000(\001\022>\n\017speech" +
      "_detector\022\022.cochlear.ai.input\032\023.cochlear" +
      ".ai.output\"\000(\001\022=\n\014event_stream\022\022.cochlea" +
      "r.ai.input\032\023.cochlear.ai.output\"\000(\0010\001\022B\n" +
      "\021age_gender_stream\022\022.cochlear.ai.input\032\023" +
      ".cochlear.ai.output\"\000(\0010\001\022C\n\022music_genre" +
      "_stream\022\022.cochlear.ai.input\032\023.cochlear.a" +
      "i.output\"\000(\0010\001\022B\n\021music_mood_stream\022\022.co" +
      "chlear.ai.input\032\023.cochlear.ai.output\"\000(\001" +
      "0\001\022F\n\025music_detector_stream\022\022.cochlear.a" +
      "i.input\032\023.cochlear.ai.output\"\000(\0010\001\022G\n\026sp" +
      "eech_detector_stream\022\022.cochlear.ai.input" +
      "\032\023.cochlear.ai.output\"\000(\0010\001B\021\n\017com.cochl" +
      "ear.aib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cochlear_ai_input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cochlear_ai_input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cochlear_ai_input_descriptor,
        new String[] { "Data", "Subtask", "Apikey", "Format", "Dtype", "Sr", });
    internal_static_cochlear_ai_output_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cochlear_ai_output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cochlear_ai_output_descriptor,
        new String[] { "Pred", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
