# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cochlear_sense.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cochlear_sense.proto',
  package='cochlear.ai',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x63ochlear_sense.proto\x12\x0b\x63ochlear.ai\"a\n\x05input\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07subtask\x18\x02 \x01(\t\x12\x0e\n\x06\x61pikey\x18\x03 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12\r\n\x05\x64type\x18\x05 \x01(\t\x12\n\n\x02sr\x18\x06 \x01(\x05\"\x16\n\x06output\x12\x0c\n\x04pred\x18\x07 \x01(\t2\x8a\x07\n\x0e\x63ochlear_sense\x12\x34\n\x05\x65vent\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12\x39\n\nage_gender\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12\x38\n\tmusic_key\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12:\n\x0bmusic_tempo\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12:\n\x0bmusic_genre\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12\x39\n\nmusic_mood\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12=\n\x0emusic_detector\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12>\n\x0fspeech_detector\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x12=\n\x0c\x65vent_stream\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x30\x01\x12\x42\n\x11\x61ge_gender_stream\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x30\x01\x12\x43\n\x12music_genre_stream\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x30\x01\x12\x42\n\x11music_mood_stream\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x30\x01\x12\x46\n\x15music_detector_stream\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x30\x01\x12G\n\x16speech_detector_stream\x12\x12.cochlear.ai.input\x1a\x13.cochlear.ai.output\"\x00(\x01\x30\x01\x62\x06proto3')
)




_INPUT = _descriptor.Descriptor(
  name='input',
  full_name='cochlear.ai.input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='cochlear.ai.input.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtask', full_name='cochlear.ai.input.subtask', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apikey', full_name='cochlear.ai.input.apikey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='cochlear.ai.input.format', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='cochlear.ai.input.dtype', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sr', full_name='cochlear.ai.input.sr', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=134,
)


_OUTPUT = _descriptor.Descriptor(
  name='output',
  full_name='cochlear.ai.output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pred', full_name='cochlear.ai.output.pred', index=0,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['input'] = _INPUT
DESCRIPTOR.message_types_by_name['output'] = _OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

input = _reflection.GeneratedProtocolMessageType('input', (_message.Message,), dict(
  DESCRIPTOR = _INPUT,
  __module__ = 'cochlear_sense_pb2'
  # @@protoc_insertion_point(class_scope:cochlear.ai.input)
  ))
_sym_db.RegisterMessage(input)

output = _reflection.GeneratedProtocolMessageType('output', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUT,
  __module__ = 'cochlear_sense_pb2'
  # @@protoc_insertion_point(class_scope:cochlear.ai.output)
  ))
_sym_db.RegisterMessage(output)



_COCHLEAR_SENSE = _descriptor.ServiceDescriptor(
  name='cochlear_sense',
  full_name='cochlear.ai.cochlear_sense',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=161,
  serialized_end=1067,
  methods=[
  _descriptor.MethodDescriptor(
    name='event',
    full_name='cochlear.ai.cochlear_sense.event',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='age_gender',
    full_name='cochlear.ai.cochlear_sense.age_gender',
    index=1,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_key',
    full_name='cochlear.ai.cochlear_sense.music_key',
    index=2,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_tempo',
    full_name='cochlear.ai.cochlear_sense.music_tempo',
    index=3,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_genre',
    full_name='cochlear.ai.cochlear_sense.music_genre',
    index=4,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_mood',
    full_name='cochlear.ai.cochlear_sense.music_mood',
    index=5,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_detector',
    full_name='cochlear.ai.cochlear_sense.music_detector',
    index=6,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='speech_detector',
    full_name='cochlear.ai.cochlear_sense.speech_detector',
    index=7,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='event_stream',
    full_name='cochlear.ai.cochlear_sense.event_stream',
    index=8,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='age_gender_stream',
    full_name='cochlear.ai.cochlear_sense.age_gender_stream',
    index=9,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_genre_stream',
    full_name='cochlear.ai.cochlear_sense.music_genre_stream',
    index=10,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_mood_stream',
    full_name='cochlear.ai.cochlear_sense.music_mood_stream',
    index=11,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='music_detector_stream',
    full_name='cochlear.ai.cochlear_sense.music_detector_stream',
    index=12,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='speech_detector_stream',
    full_name='cochlear.ai.cochlear_sense.speech_detector_stream',
    index=13,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COCHLEAR_SENSE)

DESCRIPTOR.services_by_name['cochlear_sense'] = _COCHLEAR_SENSE

# @@protoc_insertion_point(module_scope)
